// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDispatchRepository is a mock of DispatchRepository interface.
type MockDispatchRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDispatchRepositoryMockRecorder
}

// MockDispatchRepositoryMockRecorder is the mock recorder for MockDispatchRepository.
type MockDispatchRepositoryMockRecorder struct {
	mock *MockDispatchRepository
}

// NewMockDispatchRepository creates a new mock instance.
func NewMockDispatchRepository(ctrl *gomock.Controller) *MockDispatchRepository {
	mock := &MockDispatchRepository{ctrl: ctrl}
	mock.recorder = &MockDispatchRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDispatchRepository) EXPECT() *MockDispatchRepositoryMockRecorder {
	return m.recorder
}

// UpdateDriverStatus mocks base method.
func (m *MockDispatchRepository) UpdateDriverStatus(driverID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDriverStatus", driverID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDriverStatus indicates an expected call of UpdateDriverStatus.
func (mr *MockDispatchRepositoryMockRecorder) UpdateDriverStatus(driverID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDriverStatus", reflect.TypeOf((*MockDispatchRepository)(nil).UpdateDriverStatus), driverID, status)
}