// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTranslogRepository is a mock of TranslogRepository interface.
type MockTranslogRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTranslogRepositoryMockRecorder
}

// MockTranslogRepositoryMockRecorder is the mock recorder for MockTranslogRepository.
type MockTranslogRepositoryMockRecorder struct {
	mock *MockTranslogRepository
}

// NewMockTranslogRepository creates a new mock instance.
func NewMockTranslogRepository(ctrl *gomock.Controller) *MockTranslogRepository {
	mock := &MockTranslogRepository{ctrl: ctrl}
	mock.recorder = &MockTranslogRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslogRepository) EXPECT() *MockTranslogRepositoryMockRecorder {
	return m.recorder
}

// SaveOrder mocks base method.
func (m *MockTranslogRepository) SaveOrder(orderID, userID, status, serviceType string, itemDimension float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveOrder", orderID, userID, status, serviceType, itemDimension)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveOrder indicates an expected call of SaveOrder.
func (mr *MockTranslogRepositoryMockRecorder) SaveOrder(orderID, userID, status, serviceType, itemDimension interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveOrder", reflect.TypeOf((*MockTranslogRepository)(nil).SaveOrder), orderID, userID, status, serviceType, itemDimension)
}
