pipeline {
    agent any

    tools {
        go 'go-1.21' 
    }

    environment {
        SERVICE_NAME = "dispatch-service"
        DOCKER_IMAGE = "drikz/${SERVICE_NAME}:${env.BUILD_NUMBER}"
    }

    stages {
        stage('1. Checkout Repo') {
            steps {
                checkout scm
            }
        }

        stage('2. Unit Tests') {
            steps {
                dir("${SERVICE_NAME}") {
                    sh 'GOWORK=off go test -v ./... -skip Functional' 
                }
            }
        }

        stage('3. Lint/Vet') {
            steps {
                dir("${SERVICE_NAME}") {
                    sh 'GOWORK=off go vet ./...'
                }
            }
        }

        stage('4. Build & Push Image') {
            steps {
                dir("${SERVICE_NAME}") {
                    sh "docker build -t ${DOCKER_IMAGE} ."
                    
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-login', passwordVariable: 'DOCKER_PASS', usernameVariable: 'DOCKER_USER')]) {
                        sh 'echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin'
                        sh "docker push ${DOCKER_IMAGE}"
                    }
                }
            }
        }

        stage('5. Functional Tests') {
            steps {
                dir("${SERVICE_NAME}") {
                    sh 'GOWORK=off go test -v -run Functional ./... || exit 0'
                }
            }
        }

        stage('6. Deploy & Verify K8s') {
            steps {
                dir("${SERVICE_NAME}") {
                    // Replace registry tag di manifest k8s kamu
                    sh "sed -i 's|my-registry/${SERVICE_NAME}:latest|${DOCKER_IMAGE}|g' k8s/deployment.yaml"
                    
                    // Kerennya di sini: Karena tipe 'Secret file', Jenkins otomatis menyediakan path file 
                    // konfigurasi tersebut lewat variabel rahasia ini, tinggal panggil pakai --kubeconfig!
                    withCredentials([file(credentialsId: 'k8s-config', variable: 'KUBECONFIG')]) {
                        sh "kubectl --kubeconfig=\$KUBECONFIG apply -f k8s/ --validate=false"
                        sh "kubectl --kubeconfig=\$KUBECONFIG rollout status deployment/dispatch-service --timeout=90s"
                    }
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline untuk ${SERVICE_NAME} selesai dieksekusi."
        }
    }
}