apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatch-service # Sesuaikan nama
  labels:
    app: dispatch-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dispatch-service
  template:
    metadata:
      labels:
        app: dispatch-service
    spec:
      containers:
      - name: dispatch-service
        image: my-registry/dispatch-service:latest
        ports:
        - containerPort: 8003 # Pakai jatah Port Dispatch
        env:
        - name: DB_HOST
          value: "db-postgres-service"
        - name: DB_NAME
          value: "db_dispatch" # Sesuai strategi database tim
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "123"