// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLocationRepository is a mock of LocationRepository interface.
type MockLocationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLocationRepositoryMockRecorder
}

// MockLocationRepositoryMockRecorder is the mock recorder for MockLocationRepository.
type MockLocationRepositoryMockRecorder struct {
	mock *MockLocationRepository
}

// NewMockLocationRepository creates a new mock instance.
func NewMockLocationRepository(ctrl *gomock.Controller) *MockLocationRepository {
	mock := &MockLocationRepository{ctrl: ctrl}
	mock.recorder = &MockLocationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocationRepository) EXPECT() *MockLocationRepositoryMockRecorder {
	return m.recorder
}

// SaveLocation mocks base method.
func (m *MockLocationRepository) SaveLocation(userID string, lat, lon float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveLocation", userID, lat, lon)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveLocation indicates an expected call of SaveLocation.
func (mr *MockLocationRepositoryMockRecorder) SaveLocation(userID, lat, lon interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveLocation", reflect.TypeOf((*MockLocationRepository)(nil).SaveLocation), userID, lat, lon)
}